sudo: required

dist: bionic

language: ruby
rvm:
  - 2.5.5

services:
  - docker

before_install:
  - sudo apt install mongodb zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev nodejs git imagemagick libmagickwand-dev

before_script:
  - bundle exec rake assets:precompile

script:
  - bundle exec rspec spec